#!/usr/bin/expect

spawn rm -fr output
spawn vue init .. output

expect "Project name" { send "output\n"}
expect "Project description" { send "The description of my wonderful extension\n" }
expect "Author" { send "John Smith <john@smith.com>\n" }

set choice [expr $::env(USE_ROUTER) == true ? "y" : "n"]
expect "Install vue-router?" { send "$choice\n" }

set choice [expr $::env(USE_VUEX) == true ? "y" : "n"]
expect "Install vuex?" {send "$choice\n" }

set choice [expr $::env(USE_AXIOS) == true ? "y" : "n"]
expect "Install axios?" { send "$choice\n" }

expect "Install ESLint?" { send "y\n" }
expect "Standard" { send "\n" }

expect "Install Prettier?" { send "y\n" }

expect "vue-cli · Generated" { send "\n"}
